name: build
on: [push, pull_request]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:

    - name: Check out repository code
      uses: actions/checkout@v3

    - name: build and push latest image
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        docker build -t adobromilskiy/quake3-server:latest .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-server:latest

    - name: build and push branched image
      if: github.event_name == 'push'
      run: |
        docker build -t adobromilskiy/quake3-server:${{ github.ref_name }} .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-server:${{ github.ref_name }}

    - name: build and push tagged image
      if: github.event_name == 'push' && github.event.ref_type == 'tag'
      run: |
        GIT_TAG="${GITHUB_REF#refs/tags/}"
        docker build -t adobromilskiy/quake3-server:${GIT_TAG} .
        docker login --username ${{ secrets.DOCKERHUB_USER }} --password ${{ secrets.DOCKERHUB_PASSWD }}
        docker push adobromilskiy/quake3-server:${GIT_TAG}
        docker tag adobromilskiy/quake3-server:${GIT_TAG} adobromilskiy/quake3-server:latest
        docker push adobromilskiy/quake3-server:latest
